name: Deploy Docusaurus website to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. 安装 pnpm
      - name: Setup pnpm
        run: npm install -g pnpm

      # 3. 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 4. 构建网站
      - name: Build the website
        run: pnpm run build

      # 5. 清理 Git 工作区
      - name: Pre-deployment cleanup
        run: |
          git worktree prune
          git gc --prune=now
          rm -rf github-pages-deploy-action-temp-deployment-folder || true

      # 6. 设置文件夹权限
      - name: Set folder permissions
        run: |
          chmod -R +rw .

      # 7. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true
          workspace: ./custom-temp-deployment-folder
          debug: true
          token: ${{ secrets.GITHUB_TOKEN }}
